#---------------#
# Site settings #
#---------------#

url: http://labscn-unalmed.github.io
title: Laboratorio de Sistemas Complejos Naturales
subtitle: Universidad Nacional de Colombia - Sede Medellín
simple_search: https://www.google.com/search
description: Facultad de Ciencias - Escuela de Geociencias
baseurl: ""

collections:
  cartografia-digital:
    output: true
    title: Cartografía Digital
    main: 1
    description: Conceptos básicos y funcamentales de los Sistemas de Información Geográfica empleando el software libre GRASS GIS y ejemplos del relieve del departamento de Antioquia. En algunos ejemplos la información obtenida con GRASS se transfiere al software estadístico R para un análisis complementario más riguroso y didáctico.
  programacion-R:
    output: true
    title: Programación en R
    main: 1
    description: Le proporciona la habilidad de programar el lenguaje estadístico R para la solución de diversos propósitos desde el punto de vista de manejo de datos.
  estadistica-espacial:
    output: true
    title: Estadística Espacial
    main: 2
    description: Le proporciona al estudiante diferentes herramientas y aborda aspectos de análisis espacial en diferentes contextos.
  ecologia-numerica:
    output: true
    title: Ecología Numérica
    main: 2
    description: El curso está orientado a aplicar los procedimientos estadísticos multivariados en diferentes contextos ecológicos. Mediante procedimientos estadísticos se le otorgará al estudiante las herramientas introductorias para abordar el manejo de datos multivariados en el contexto ecológico.
  estadistica-descriptiva:
    output: true
    title: Estadística Descriptiva y<br>Análisis Exploratorio de Datos
    main: 0
    description: Permite al estudiante adquirir habilidades en el manejo de datos y en realizar análisis descrptivos y exploratorios utilizando herramientas para este propósito.
  metodos-estadisticos:
    output: true
    title: Métodos Estadísticos<br>(Diseño Experimental)
    main: 0
    description: Una visión general sobre los procedimientos estadísticos y la planeación de un diseño experimental válido desde el punto de vista científico.
  modulo-R:
    output: true
    title: Lenguajes estadísticos (Módulo R)
    main: 0
    description: Módulo del lenguaje de programación R en la asignatura lenguajes estadísticos.
  geomorfometria:
    output: true
    title: Geomorfometría
    hidden: true
  documentacion-interna:
    output: true
    title: Documentación Interna
    hidden: true

kramdown:
  toc_levels: 1..3

sass:
  style: compressed

# Google Analytics
google_analytics_tracking_id: UA-54312951-2
