#---------------#
# Site settings #
#---------------#

url: http://labscn-unalmed.github.io
title: Laboratorio de Sistemas Complejos Naturales
subtitle: Universidad Nacional de Colombia - Sede Medellín
simple_search: https://www.google.com/search
description: Facultad de Ciencias - Escuela de Geociencias
baseurl: ""
permalink: /:categories/:title/

collections:
  cartografia-digital:
    output: true
    title: Cartografía Digital
  programacion-R:
    output: true
    title: Programación en R
  estadistica-espacial:
    output: true
    title: Estadística Espacial
  estadistica-descriptiva:
    output: true
    title: Estadística Descriptiva y Análisis Exploratorio de Datos
  metodos-estadisticos:
    output: true
    title: Métodos Estadísticos (Diseño Experimental)
  documentacion-interna:
    output: true
    title: Documentación Interna

sass:
  style: compressed

gems:
  - jekyll-sitemap

# Google Analytics
google_analytics_tracking_id: UA-54312951-2
