#---------------#
# Site settings #
#---------------#

url: http://labscn-unalmed.github.io
title: Laboratorio de Sistemas Complejos Naturales
subtitle: Universidad Nacional de Colombia - Sede Medellín
simple_search: https://www.google.com/search
description: Facultad de Ciencias - Escuela de Geociencias
baseurl: ""
permalink: /:categories/:title/

sass:
  style: compressed

gems:
  - jekyll-sitemap

# Google Analytics
google_analytics_tracking_id: UA-54312951-2
