#---------------#
# Site settings #
#---------------#

url: http://labscn-test.github.io
title: Laboratorio de Sistemas Complejos Naturales
subtitle: Universidad Nacional de Colombia - Sede Medellín
simple_search: https://www.google.com/search
description: Facultad de Ciencias - Escuela de Geociencias
baseurl: ""
permalink: /:categories/:title/

# Google Analytics
google_analytics_tracking_id: UA-54312951-2

# Colections
# collections:
#   cartografia-digital:
#     output: true
#     permalink: /cartografia-digital/:path/
#   programacion-R:
#     output: true
#     permalink: /programacion-R/:path/
#   estadistica-espacial:
#     output: true
#     permalink: /estadistica-espacial/:path/
#   estadistica-descriptiva:
#     output: true
#     permalink: /estadistica-descriptiva/:path/
#   metodos-estadisticos:
#     output: true
#     permalink: /metodos-estadisticos/:path/

exclude: ['programacion-R/RClasses']