---
title: "Estructuras de flujo en R"
author: "Kenneth Roy Cabrera Torres"
date: "22 de junio de 2016"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Estructura de decisión

```{r eval=FALSE}
  if (x > 3) { 
    y <- 10
   } else { 
    y <- 0
  }
```

El resultado se puede llevar a una variable

```{r eval=FALSE}
  y <- if (x>3) { 10 } else { 0 }
```

## Estructuras de repetición
```{r eval=FALSE}
for (i in 1:10) {
  print(i)
}    
```

```{r eval=FALSE}
x < -c("a", "b", "c", "d")
for (i in 1:6) {
  print(x[i])
}
       
for (i in seq_along(x)) {
  print([i])      
}

for (letter in x) {
  print(letter)
}
```


```{r eval=FALSE}
(x <- matrix(1:6, 2, 3))

for (i in seq_len(ncol(x))) {
  print(x[i])
}  

for (i in seq_len(nrow(x))) {             
   for (j in seq_len(ncol(x))) {
     print(x[i,j])
   }
}
```

```{r eval=FALSE}
count <- 0
while (count < 10) {
 print(count)
 count <- count + 1
}

z <- 5
while (z >= 3 && z <= 10) {
  print(z)
  coin <-rbinom(1,1,0.5)
  if (coin==1) {
    z <- z + 1
  } else {
    z <- z - 1        
  }   
}


x0 <- 1
tol <- 1e-8
repeat {
  x1 <- computeEstimate()
  if ( abs(x1 - x0) < tol ) {
    break
  } else {
  x0 <- x1
  }
}
```


