---
title: "Religiones"
author: "Kenneth Cabrera"
date: "16/10/2014"
output: html_document
---

Lectura de la base de datos y arreglo de la base de datos
```{r}
relig <- read.delim("religions.csv", check.names = F, sep = ";",
                    stringsAsFactors = F)
require(reshape2)
relig2 <- melt(relig, "religion")
names(relig2) <- c("Religión", "Ingresos", "n")
head(relig2)
```

Primer intento de gráfica utilizando lattice
```{r}
require(lattice)
xyplot(n ~ Ingresos| Religión, data = relig2)
```

Segundo intento de graficación mediante lattice
```{r}
require(lattice)
xyplot(n ~ Ingresos| Religión, data = relig2,
           scales=list(x=list(rot=90)),
       main = "Ingresos por relgión en EEUU",
       xlab = "Ingresos (dólares)",
       ylab = "Número de personas")
```

Cálculo del porcentaje de cada ingreso por religión.

```{r}
religT1 <- aggregate(subset(relig2, select=n), 
          with(relig2, list(Religión = Religión)), sum)
names(religT1)[2]<-"nT"
head(relig2)
relig2 <- merge(relig2, religT1)
head(relig2)
relig2$Porcentaje <- with(relig2, n/nT*100)
head(relig2)
```

Gráfica definitiva

```{r, fig.width=14, fig.height=7}
require(lattice)
conf1 <- simpleTheme(pch = 19, col = "darkblue")
xyplot(Porcentaje ~ Ingresos| Religión, data = relig2,
           scales=list(x=list(rot=90)),
       main = "Distribución porcentual de ingresos",
       xlab = "Ingresos (dólares)",
       ylab = "Porcentaje de cada religión (%)",
       par.settings = conf1,
       layout = c(9, 2))
```

