---
title: "Análisis de correlación canónica"
author: "Kenneth Roy Cabrera Torres"
date: "Martes, 8 de noviembre de 2016"
output: 
  html_document: 
    toc: yes
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, 
                      fig.height=7)
```


## Paquetes necesarios
```{r}
require(vegan)
require(dplyr)
```

## Lectura de base de datos

```{r}
# Lectura
ambient       <- read.csv2("ambientales.csv",enc="latin1",row.names=1)
peces         <- read.csv2("peces.csv",enc="latin1",row.names=1)
locs          <- read.csv2("localidades.csv",enc="latin1",row.names=1)
nomEspec      <- read.csv2("nombresdeespecies.csv",enc="latin1")
nomVarAmbient <- read.csv2("Nombresdevariablesambientales.csv",enc="latin1")

# Adecuación
# Quitar el sitio que no tiene ninguna especie
sumEsp  <- apply(peces,1,sum)
peces   <- peces[sumEsp!=0,]
ambient <- ambient[sumEsp!=0,]
locs    <- locs[sumEsp!=0,]
ambient <- data.frame(scale(ambient))

```

## Adecuación de base de datos
```{r}
peces.hel <- decostand(peces, "hellinger")
``` 

## CCA (Canonical Correlation Analysis)

```{r}
require(CCA)
CCA1 <- cc(peces.hel, ambient)
CCA1
```

```{r}
temp1 <- data.frame(das = ambient$das, Legi = peces.hel$Legi)
require(ggplot2)
g1 <- ggplot(temp1, aes(das, Legi))
g1 + geom_jitter() + geom_smooth(method = lm)

temp2 <- data.frame(pH = ambient$pH, Chna = peces.hel$Chna)
require(ggplot2)
g1 <- ggplot(temp2, aes(pH, Chna))
g1 + geom_jitter() + geom_smooth(method = lm)

```


## Graficas del CCA

```{r}
plot(CCA1$cor, type = "b")
plt.cc(CCA1, var.label = TRUE, d1 = 1, d2 = 2, type = "b")
```

## Gráfica de las dos variables canónicas

```{r}
plot(CCA1$scores$xscores[,1],CCA1$scores$yscores[,1])
```

## Imágenes de matrices de correlación

```{r}
matriz_corr <- matcor(peces.hel, ambient)

img.matcor(matriz_corr)

img.matcor(matriz_corr, type = 2)
```

