---
title: "Similitudes s7, s8, s9, s10"
author: "Kenneth Roy Cabrera Torres"
date: "27 de octubre de 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lectura de base de datos
```{r}
datos1 <- read.csv2("similitud1.csv")
datos1
```


## Similitud de Jaccard
```{r}
require(vegan)
```

```{r}
d7 <- vegdist(datos1, method = "jaccard")
cl7 <- hclust(d7, method = "complete")
plot(cl7, hang = -1, main = "jaccard")
```

```{r}
d8 <- designdist(datos1, 
                  "1-(2 * a)/(2 * a + b + c)", 
                  abcd = TRUE)
cl8 <- hclust(d8, method = "complete")
plot(cl8, hang = -1, main = "sorensen")
```

```{r}
d9 <- designdist(datos1, 
                  "1-(3 * a)/(3 * a + b + c)", 
                  abcd = TRUE)
cl9 <- hclust(d9, method = "complete")
plot(cl9, hang = -1, main = "S9")
```


```{r}
d10 <- designdist(datos1, 
                  "1- a/(a + 2*b + 2*c)", 
                  abcd = TRUE)
cl10 <- hclust(d10, method = "complete")
plot(cl10, hang = -1, main = "S10")
```

```{r, fig.width=9}
op <- par(no.readonly = TRUE)
par(mfrow = c(1,4))
plot(cl7, hang = -1, las = 1, main = "jaccard")
plot(cl8, hang = -1, las = 1, main = "sorensen")
plot(cl9, hang = -1, las = 1, main = "D9")
plot(cl10, hang = -1, las = 1, main = "D10")
par(op)
```

```{r}
require(ecodist)
vlab <- as.vector(lower(outer(1:nrow(datos1), 1:nrow(datos1),
                        paste, sep = "-")))
vd9 <- as.vector(d9)
vd10 <- as.vector(d10)

plot(vd9, vd10, type = "n", ylim = c(0, 1), xlim = c(0, 1), asp = 1)
text(vd9, vd10, labels = vlab)

```

