---
title: "Projectar una imagen escaneada"
output: html_notebook
---



## Lectura de la imagen escaneada

```{r}
require(raster)
Nucl_Rio <- brick("nucleo_rio1.tif")
plotRGB(Nucl_Rio)
```

## Estableder las coordenadas geográficas de las esquinas

```{r}
extent(Nucl_Rio) <- c(-75.574995, -75.573117, 6.262784, 6.264687)
```

## Mostrar el mapa en las nuevas coordenadas

```{r}
projection(Nucl_Rio) <- CRS("+proj=longlat +datum=WGS84")
plotRGB(Nucl_Rio)
```

## Proyectar mapa en coordenadas planas (Magnas Sirgas, Bogotá)

```{r}
require(rgdal)
CRSdest <- CRS("+init=epsg:3116")
Nucl_Rio2 <- projectRaster(Nucl_Rio, crs = CRSdest)
plotRGB(Nucl_Rio2)
```

## Lectura de datos en coordenadas geográficas

```{r}
datos <- read.csv2("datos.csv")

with(datos, plot(long, lat, asp = 1, pch = 19, col = "blue"))
```

```{r}
plotRGB(Nucl_Rio, addfun = points(datos$long, datos$lat, pch = 19, col = "blue"))
```


## Otra forma de interpolar

```{r}
require(akima)
interp_akima <- interp.new(x = datos[,1], y = datos[,2], z = datos[,3],
                      xo= seq(min(datos[,1]), max(datos[,1]), length = 400),
                      yo=seq(min(datos[,2]), max(datos[,2]), length = 400),                      
                      linear = FALSE, extrap = FALSE)
image(interp_akima, asp = 1)
points(datos[,c(1,2)], pch = 19)
```

```{r}
interp_akima_rast <- raster(interp_akima)
plotRGB(Nucl_Rio, addfun = points(datos$long, datos$lat, pch = 19, col = "blue"))
plot(interp_akima_rast, add = TRUE, alpha = 0.6)
```
```{r}
datos1 <- datos
long.range <- range(datos1$long) 
lat.range  <- range(datos1$lat)
proporcion <- 0.1
margenes.long <- diff(long.range)*proporcion
margenes.lat  <- diff(lat.range)*proporcion
long.range[1] <- long.range[1] - margenes.long
long.range[2] <- long.range[2] + margenes.long
lat.range[1]  <- lat.range[1] - margenes.lat
lat.range[2]  <- lat.range[2] + margenes.lat
grd <- expand.grid(long = seq(from = long.range[1], to = long.range[2], l = 200 ),
                   lat = seq(from = lat.range[1], to = lat.range[2], l = 200))  
require(automap)
coordinates(datos1) <- ~ long + lat
coordinates(grd) <- ~ long + lat
gridded(grd) <- TRUE
pred_kriging <- autoKrige(z ~ 1, datos1, grd)
plot(pred_kriging)
```

```{r}
krig_raster <- raster(pred_kriging$krige_output)
projection(krig_raster) <-  CRS("+proj=longlat +datum=WGS84")
plotRGB(Nucl_Rio, addfun = points(datos$long, datos$lat, pch = 19, col = "black"))
plot(krig_raster, add = TRUE, alpha = 0.5)
```

```{r}
krig_raster <- raster(pred_kriging$krige_output)
projection(krig_raster) <-  CRS("+proj=longlat +datum=WGS84")
plotRGB(Nucl_Rio, addfun = points(datos$long, datos$lat, pch = 19, col = "black"))
plot(krig_raster, add = TRUE, alpha = 0.5, col = rev(heat.colors(100)))
```


```{r}
krig_raster <- raster(pred_kriging$krige_output)
projection(krig_raster) <-  CRS("+proj=longlat +datum=WGS84")
plotRGB(Nucl_Rio, addfun = points(datos$long, datos$lat, pch = 19, col = "black"))
plot(krig_raster, add = TRUE, alpha = 0.5, col = colorRampPalette(c("blue","green","yellow","red"))(100))
```


