---
title: "Encuesta a estudiantes de EDAED"
author: "Kenneth Roy Cabrera Torres"
date: "Jueves, 15 de febrero de 2018"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Lectura de la base de base de datos.
library(readxl)
encuesta <- read_excel("encuesta1.xlsx")
```

## Estadísticos básicos de PAPA y porcentaje

### PAPA
```{r}
summary(encuesta$papa)
```

### Porcentaje.

```{r}
summary(encuesta$porcentaje)
```


## Gráfica preliminar.

```{r}
plot(encuesta$papa, encuesta$porcentaje)
```

## Cálculos para establecer el verdadero porcentaje

```{r}
encuesta$papa
rank(encuesta$papa)
(1 - rank(encuesta$papa)/length(encuesta$papa))*100
encuesta$vporcentaje <- (1 - rank(encuesta$papa)/length(encuesta$papa))*100
```

## Gráfica porcentaje verdadero vs porcentaje estimado.

```{r}
with(encuesta, plot(vporcentaje, porcentaje, pch = 19,
                    main = "Porcentaje verdadero vs porcentaje estimado",
     xlab = "Porcentaje verdadero",
     ylab = "Porcentaje estimado", 
     las = 1))
abline(c(0, 1), col = "red")
abline(lm(encuesta$porcentaje ~ encuesta$vporcentaje), col = "blue")
legend("bottomright", legend = c("Tendencia lineal",
                              "Linea y=x"),
       lty = 1, col = c("blue", "red"))
grid()
```

