---
title: "Análisis Exploratorio Encuesta"
author: "Universidad Nacional de Colombia, Sede Medellín"
date: "11 de agosto de 2015"
output: 
  html_document: 
    highlight: tango
    toc: yes
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, 
                      fig.height=7)
```

## Lectura de la base de datos
```{r}
# Lee la base de datos.
encuesta <- read.csv2("Encuesta2.csv", encoding = "latin1")
# Muestra los primero 6 regístros de la base de datos.
head(encuesta)
# Nombra algunas codificaciones en la base de datos.
# Género
encuesta$Género <- factor(encuesta$Género, labels = c("Femenino","Masculino"))
# Carrera
encuesta$Carrera <- factor(encuesta$Carrera, labels = c("Estadística","Ingeniería Forestal", "Ingeniería de Sistemas"))

# Separa la hora de llegada
hora <- as.numeric(substring(encuesta$Hora.llegada, 1, 2))
# Separa los minutos de la hora
minutos <- as.numeric(substring(encuesta$Hora.llegada, 4, 5))

# Se cre auna nueva variable con la hora de llegada
encuesta$Hora.llegada2 <- hora + minutos/60

# Se crea una nueva variable con los minutos que llega antes o después de la hora
encuesta$minutosT <- ifelse(encuesta$Hora.llegada2 < 7, 
                            encuesta$Hora.llegada2 - 6, 
                            encuesta$Hora.llegada2 - 8)*60

# Muestra los primero 6 regístros de la base de datos, con las correcciones
head(encuesta)

```

## Analisis exploratorio preliminar
```{r}
# Resumen de toda la base de datos
summary(encuesta)
```

## Análsis exploratorio de algunas variables

### Número aleatorio

Distribución de frecuencia
```{r}
(tn1 <- with(encuesta, table(Número)))

barplot(tn1, main = "Distribución de números 'aleatorios' ")
```

Distribución porcentual
```{r}
(tnp <- tn1/sum(tn1)*100)

barplot(tnp, main = "Distribución porcentual de los números 'aleatorios'")
grid()
```

### Género
```{r}
# Conteo de personas por género
(t1 <- with(encuesta, table(Género)))
# Distribución porcentual
(t1p <- t1/sum(t1)*100)
```

```{r}
bp1 <- barplot(t1p, main = "Distribución porcentual por género",
        ylab = "Porcentaje (%)")
text(bp1,t1p, paste(round(t1p,1),"% ","(",t1,")", sep = ""), pos = 1)
```

### Hora de llegada a la Universidad
```{r}
hist(encuesta$Hora.llegada2, main = "Histograma de la hora de llegada a la U",
     ylab = "Frencuencia", xlab = "Hora de llegada")
```

### Distribución de los minutos antes o después de la hora
```{r}
h1 <- hist(encuesta$minutosT, main = "Histograma de minutos",
     ylab = "Frecuencia", xlab = "Minutos con respecto a la hora",
     nclass = 20, axes = FALSE, ylim = c(0,22), col = "gray80")
axis(1, at = seq(-40,130, 10))
axis(2, at = seq(0,22, 2))
abline(v = 0, col = "red")
abline(h = seq(0,22, 2), col = "gray90", lty = 2)
```

### Resultados numéricos del histograma
```{r}
h1
```

### Relación de llegar puntuale y el PAPA
```{r}
require(ggplot2)
g1 <- ggplot(encuesta, aes(minutosT, PAPA))
g1 + geom_point(size = 3) + geom_smooth(size=2) +
     ggtitle("Relación minutos y PAPA") +
     xlab("Minutos con respecto a la hora de llegada")

```


