---
title: "Análisis Exploratorio Encuesta"
author: "Universidad Nacional de Colombia, Sede Medellín"
date: "11 de agosto de 2015"
output: 
  html_document: 
    highlight: tango
    toc: yes
---

## Lectura de la base de datos
```{r}
# Lee la base de datos.
encuesta <- read.csv2("Encuesta.csv", encoding = "latin1")
# Muestra los primero 6 regístros de la base de datos.
head(encuesta)
# Nombra algunas codificaciones en la base de datos.
# Género
encuesta$Género <- factor(encuesta$Género, labels = c("Femenino","Masculino"))
# Carrera
encuesta$Carrera <- factor(encuesta$Carrera, labels = c("Estadística","Ingeniería Forestal", "Ingeniería de Sistemas"))
# Muestra los primero 6 regístros de la base de datos, con las correcciones
head(encuesta)
```

## Analisis exploratorio preliminar
```{r}
# Resumen de toda la base de datos
summary(encuesta)
```

## Análsisi exploratorio de algunas variables
### Edad
```{r}
# Estadísticos básicos de Edad
with(encuesta, summary(Edad))
# Desviación estándar de edad
with(encuesta, sd(Edad))
```

```{r}
# Gráfica de puntos de Edad
with(encuesta, plot(rep(1,length(Edad)),Edad, main="Diagrama de puntos de Edad",
                    pch=19, axes=FALSE, xlab="", ylab="Edad (años cumplidos)"))
box()
axis(2)

with(encuesta, plot(Encuesta,Edad, main="Diagrama de puntos de Edad",
                    pch=19, axes=FALSE, 
                    xlab="Número de encuesta", ylab="Edad (años cumplidos)"))
box()
axis(1)
axis(2)

with(encuesta, dotchart(Edad, main="Diagama de puntos", pch = 19))

with(encuesta, dotchart(sort(Edad), main="Diagama de puntos", pch = 19))

require(ggplot2)
g1 <- ggplot(encuesta, aes(Edad))
g1 + geom_dotplot() +
     ggtitle("Distribución de edades")+
     scale_y_continuous("", breaks = NULL) +
     scale_x_continuous(name="Edad (años cumplidos)", 
                        breaks=16:30,limits=c(16, 30))+
      
     theme(
      plot.title = element_text(size=22),
      axis.title.y = element_text(size=20),
      axis.title.x = element_text(size=20),
      axis.text.x=
        element_text(size = 20, color = "black"), 
      axis.text.y=
       element_text(color="black", size= 20))

# Gráfica de barras no apropiada
tablaEdades <- table(encuesta$Edad)
tablaEdades
with(encuesta,barplot(tablaEdades,
                      main="Distribución de edades",
                      ylab="Frecuencia absoluta",
                      xlab="Edad (cumplida en años)",
                      ylim = c(0,20)))

# Gráfica mejorada
tablaEdades2 <- table(cut(encuesta$Edad,seq(16,30),
                          include.lowest=TRUE,
                          right = FALSE))
tablaEdades2

with(encuesta,barplot(tablaEdades2,
                      main="Distribución de edades",
                      ylab="Frecuencia absoluta",
                      xlab="Edad (cumplida en años)",
                      ylim = c(0,20), las = 2, cex.names = 0.8))

# Diagrama de caja y bigotes
with(encuesta, boxplot(Edad, main = "Distribución de las Edades"))

# Combinados con puntos
with(encuesta, boxplot(Edad, main = "Distribución de las Edades", pch = 19))
with(subset(encuesta,Edad<=24), points(jitter(rep(1,length(Edad)),factor = 5),Edad,
                      pch=18))
```

