---
title: "Preguntas frecuentes"
author: "Kenneth Cabrera"
date: "20 de noviembre de 2015"
output: html_document
---

Lectura de tres meses de la base de datos de EMA.
```{r}
abr2014 <- read.csv2("Abr 2014.csv")
abr2015 <- read.csv2("Abr 2015.csv")
ago2013 <- read.csv2("Ago 2013.csv")
```

## Unir bases de datos por fila
Unir por columnas las tres bases de datos aún cuando el 
número de columnas no es el mismo
```{r}
require(plyr)
totalEMA <- rbind.fill(abr2014,abr2015, ago2013)
```

## Convertir a formato fecha
Convertir al formato fecha de manera adecuada.

```{r}
require(stringr)
# Extrae hora y minutos
horas_min <- str_extract(totalEMA$Time, "[0-9]*:[0-9]{2}")
# Extrae si son am o pm.
am_pm <-str_extract(totalEMA$Time, "[AP]M")
# Crea una nueva variable de hora
hora2 <- paste(horas_min, am_pm)
# Combina la fecha con la nueva hora
fecha_comb <- paste(totalEMA$Date, hora2, sep = "-")
# Crea una nueva variable en formato fecha y la convierte a tipo fecha
totalEMA$Fecha <- as.POSIXct(strptime(fecha_comb,format = "%d/%m/%Y-%I:%M %p"))
```

