---
title: "Interpolación espacial"
author: "Kenneth Cabrera"
date: "8 de noviembre de 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Paquetes necesarios

```{r}
library(ggplot2)
library(gstat)
library(sp)
library(maptools)
```


## Lectura de la base de datos

```{r}
estonia_air_temperature_2 <- read.csv(file = "estonia_air_temperature_2.csv", 
    header = TRUE)
```

## Adecuación de la base de datos

```{r}
estonia_air_temperature_2_test <- estonia_air_temperature_2 
estonia_air_temperature_2_test$x <- estonia_air_temperature_2_test$lon
estonia_air_temperature_2_test$y <- estonia_air_temperature_2_test$lat
coordinates(estonia_air_temperature_2_test) = ~x + y
```

## Despliegue de lao datos espaciales

```{r}
plot(estonia_air_temperature_2_test)
```

## Definición de la rejilla de predicción

```{r}
x.range <- range(estonia_air_temperature_2_test$x) 
y.range <- range(estonia_air_temperature_2_test$y)
proporcion <- 0.1
margenes.x <- diff(x.range)*proporcion
margenes.y <- diff(y.range)*proporcion
x.range[1] <- x.range[1] - margenes.x
x.range[2] <- x.range[2] + margenes.x
y.range[1] <- y.range[1] - margenes.y
y.range[2] <- y.range[2] + margenes.y
grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by = 0.05 ),
                   y = seq(from = y.range[1], to = y.range[2], by = 0.05))  
coordinates(grd) <- ~x + y
gridded(grd) <- TRUE
```

## Mapa de la interpolación por inverso del cuadraro de la distancia

```{r}
plot(grd, cex = 1.5, col = "grey")
points(estonia_air_temperature_2_test, pch = 1, col = "red", cex = 1)
```

```{r}
idw <- idw(formula = may12 ~ 1, locations = estonia_air_temperature_2_test, newdata = grd)  
idw.output = as.data.frame(idw)  
names(idw.output)[1:3] <- c("long", "lat", "var1.pred")
```

## Mapa final de resultados (idp = 2)
```{r}
require(ggplot2)
ggplot() + geom_raster(data = idw.output, aes(x = long, y = lat, fill = var1.pred)) + 
    scale_fill_gradientn(colours = c("darkblue", "blue", "lightblue4", "lightblue")) +
    geom_point(data = estonia_air_temperature_2, aes(x = lon, y = lat), shape = 19, 
        colour = "red") + coord_fixed() + scale_colour_gradient()
```

```{r}
idw <- idw(formula = may12 ~ 1, locations = estonia_air_temperature_2_test, newdata = grd,
           idp = 0.5)  
idw.output = as.data.frame(idw)  
names(idw.output)[1:3] <- c("long", "lat", "var1.pred")
```

## Mapa final de resultados (idp = 0.5)
```{r}
require(ggplot2)
ggplot() + geom_raster(data = idw.output, aes(x = long, y = lat, fill = var1.pred)) + 
    scale_fill_gradientn(colours = c("darkblue", "blue", "lightblue4", "lightblue")) +
    geom_point(data = estonia_air_temperature_2, aes(x = lon, y = lat), shape = 19, 
        colour = "red") + coord_fixed() + scale_colour_gradient()
```
