---
title: "Resumen de base de datos"
author: "Universidad Nacional de Colombia, Sede Medellín"
date: "Jueves, 29 de octubre de 2015"
output: 
  html_document: 
    highlight: haddock
    toc: yes
---



```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, 
                      fig.height=8)
```


## Lectura de las bases de datos

```{r}
NBI_vs_DesempF <- read.csv2("NBI_vs_DesempeñoFiscal.csv")
Poblacion <- read.csv2("poblacion_col.csv")
```

## Unir bases de datos
```{r}
total <- merge(NBI_vs_DesempF, Poblacion,
               by.x = "Codigo_mun",
               by.y = "COD_POB")
head(total)
tail(total)
summary(total)
```


## Preguntas específicas a la base de datos.

### Calcular la población total del pais para 2011

```{r}
with(total, sum(Total_2011))

require(dplyr)
total %>% summarise(sumaPob = sum(Total_2011))
```

### Calcular la población por departamento
```{r}
with(total, tapply(Total_2011, Dpto, sum))
# De manera ordenada
sort(with(total, tapply(Total_2011, Dpto, sum)))
# De manera ordenada descendentemente
sort(with(total, tapply(Total_2011, Dpto, sum)), decreasing = TRUE)
# Con el paquete dplyr
require(dplyr)
totalDpto <- total %>% group_by(Dpto) %>% summarise(sumaPob = sum(Total_2011))
totalDpto
totalDpto %>% as.data.frame()
totalDpto %>% arrange(sumaPob)
totalDpto %>% arrange(desc(sumaPob))
totalDpto %>% arrange(desc(sumaPob)) %>% as.data.frame()
```

### Estadísticas desempeño fiscal por departamento
```{r}
require(dplyr)
total %>% 
  group_by(Dpto) %>% 
  summarise(mediaDF = mean(Desemp_fiscal),
            deDF = sd(Desemp_fiscal),
            N = length(Desemp_fiscal)) %>%
  arrange(desc(mediaDF)) %>%
  as.data.frame()
```


  